substitutions:
  _SERVICE: symphonia-api
  _REGION: europe-west2
  _AR_REPO: cloud-run-source-deploy
  _IMAGE_NAMESPACE: symphonia
  _IMAGE_NAME: symphonia-api
  _GITHUB_TOKEN_SECRET: GITHUB_TOKEN

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    entrypoint: bash
    secretEnv:
      - GITHUB_TOKEN
    args:
      - -ceu
      - |
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}"
        docker build --no-cache \
          --build-arg GITHUB_TOKEN="$$GITHUB_TOKEN" \
          -t "$IMAGE" \
          backend -f backend/Dockerfile

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE}
      - --platform=managed
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}
      - --region=${_REGION}
      - --quiet

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_GITHUB_TOKEN_SECRET}/versions/latest
      env: GITHUB_TOKEN

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
