substitutions:
  _SERVICE: symphonia-api
  _REGION: europe-west2
  _AR_REPO: cloud-run-source-deploy
  _IMAGE_NAMESPACE: symphonia
  _IMAGE_NAME: symphonia-api

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    entrypoint: bash
    args:
      - -ceu
      - |
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}"
        docker build --no-cache \
          -t "$$IMAGE" \
          backend -f backend/Dockerfile

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE}
      - --platform=managed
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}
      - --region=${_REGION}
      - --quiet

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: RouteTraffic
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_SERVICE}
      - --platform=managed
      - --to-latest
      - --region=${_REGION}
      - --quiet

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAMESPACE}/${_IMAGE_NAME}:${COMMIT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
