// @ts-nocheck
// Generated by clean-synthesis-controls.cjs. Synthetic, no API calls.
import * as o from 'react';
import * as e from 'react/jsx-runtime';
const kn={},ct={};const Cn=()=>({}),Sn=()=>[];const es=v=>typeof v==='number'?'$'+v.toFixed(2):'—';const Rr=()=>null;
const be=({children,onClick,disabled,loading})=>e.jsx('button',{onClick,disabled:disabled||loading,className:'synthesis-preview-generate',children:loading?'Generating…':children});
const Ft=()=>e.jsx('p',{children:'A synthetic draft for reviewing the layout. The claims and original responses remain below.'});
function lt({
  activeRound: s,
  contextNote: t,
  canGenerate: a = !1,
  onGenerate: d,
  editor: u,
  isDirty: n,
  isSaving: l,
  isPublished: c,
  isPublishing: i,
  onSave: m,
  onRevert: v,
  onTogglePublished: y,
  questionSpecificSynthesisQuestions: k = []
}) {
  const b = s?.synthesis || "",
    _ = b.trim().length > 0,
    N = k.length > 0,
    [C, F] = o.useState({}),
    L = N ? "Question summaries" : `Synthesis for Round ${s?.round_number || ""}`;
  function Q(A) {
    return A.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }
  function R(A, P) {
    const q = Object.fromEntries(P.map(f => [f, ""]));
    if (!A.trim() || typeof DOMParser > "u") return q;
    const S = f => f.replace(/^question\s*[:.)-]?\s*/i, "").replace(/^q\d+\s*[:.)-]?\s*/i, "").replace(/\s+/g, " ").trim().toLowerCase(),
      w = new DOMParser().parseFromString(A, "text/html");
    return Array.from(w.body.querySelectorAll("h1,h2,h3,h4,h5,h6")).forEach(f => {
      const T = f.textContent?.trim() ?? "",
        z = S(T),
        K = P.find(W => S(W) === z);
      if (!K) return;
      const G = [];
      let ae = f.nextSibling;
      for (; ae && !(ae instanceof HTMLElement && /^H[1-6]$/.test(ae.tagName));) {
        const W = ae.textContent?.trim();
        W && G.push(W), ae = ae.nextSibling;
      }
      q[K] = G.join(`

`);
    }), q;
  }
  function j(A) {
    return k.map(P => {
      const q = (A[P] || "").split(/\n{2,}/).map(w => w.trim()).filter(Boolean),
        S = q.length ? q.map(w => `<p>${Q(w).replace(/\n/g, "<br>")}</p>`).join("") : "<p></p>";
      return `<h2>${Q(P)}</h2>${S}`;
    }).join("");
  }
  o.useEffect(() => {
    !N || !u || F(R(b || u.getHTML(), k));
  }, [s?.id, b, u, N, k.join("|")]);
  function I(A, P) {
    if (!u) return;
    const q = {
      ...C,
      [A]: P
    };
    F(q);
    const S = j(q);
    u.getHTML().trim() !== S.trim() && u.commands.setContent(S, !0);
  }
  return e.jsxs("div", {
    className: `card p-4 sm:p-5 ${N ? "" : "min-h-[220px] lg:min-h-[320px]"}`,
    children: [e.jsxs("header", {
      className: "synthesis-draft-header",
      children: [e.jsxs("div", {
        className: "synthesis-draft-title",
        children: [e.jsx("h2", {
          children: N ? "Question summaries" : "Round " + (s?.round_number || "") + " synthesis"
        }), e.jsx("span", {
          className: "synthesis-draft-state",
          children: n ? "Unsaved changes" : c ? "Published" : "Draft"
        }), t && !N && e.jsx("p", {
          className: "synthesis-draft-note",
          title: t,
          children: /carried forward from Round (\d+)/i.test(t) ? "Based on Round " + t.match(/carried forward from Round (\d+)/i)[1] + " · Save to create this round’s draft." : t
        })]
      }), e.jsxs("div", {
        className: "synthesis-draft-buttons",
        children: [!_ && a && d ? e.jsx("button", {
          type: "button",
          onClick: d,
          children: "Generate draft"
        }) : null, n || l ? e.jsxs(e.Fragment, {
          children: [e.jsx("button", {
            type: "button",
            onClick: v,
            disabled: l,
            children: "Revert"
          }), e.jsx("button", {
            type: "button",
            onClick: m,
            disabled: l,
            className: "synthesis-primary",
            children: l ? "Saving…" : "Save"
          })]
        }) : null, e.jsx("button", {
          type: "button",
          onClick: y,
          disabled: i || !_ && !c,
          className: "synthesis-publish",
          children: i ? "Updating…" : c ? "Hide from survey" : "Publish to survey"
        })]
      })]
    }), N ? e.jsx("div", {
      className: "space-y-2",
      children: k.map((A, P) => e.jsxs("div", {
        className: "py-2",
        style: {
          borderBottom: P < k.length - 1 ? "1px solid color-mix(in srgb, var(--border) 58%, transparent)" : "none"
        },
        children: [e.jsxs("label", {
          className: "mb-2 flex items-start gap-2 text-sm font-medium",
          style: {
            color: "var(--foreground)"
          },
          children: [e.jsx("span", {
            className: "mt-0.5 inline-flex h-5 min-w-5 items-center justify-center rounded-md text-[11px] font-semibold",
            style: {
              backgroundColor: "var(--muted)",
              color: "var(--muted-foreground)"
            },
            children: P + 1
          }), e.jsx("span", {
            children: A
          })]
        }), e.jsx("textarea", {
          value: C[A] || "",
          onChange: q => I(A, q.target.value),
          rows: 2,
          className: "w-full resize-none rounded-lg px-3 py-2.5 text-sm leading-6 outline-none transition-colors",
          style: {
            border: "1px solid color-mix(in srgb, var(--border) 76%, transparent)",
            backgroundColor: "var(--background)",
            color: "var(--foreground)"
          },
          placeholder: "Previous-round context for this question"
        })]
      }, A))
    }) : null, N ? null : e.jsx("div", {
      className: "rounded-xl px-3 py-3 sm:px-4 sm:py-4",
      style: {
        backgroundColor: "var(--background)",
        border: "1px solid color-mix(in srgb, var(--border) 82%, transparent)",
        minHeight: "14rem"
      },
      children: e.jsx(Ft, {
        editor: u
      })
    })]
  });
}
function dt({
  synthesisMode: s,
  onModeChange: t,
  selectedModel: a,
  onModelChange: d,
  models: u,
  estimateLabel: n,
  responseCount: l,
  isGenerating: c,
  onGenerate: i,
  openRouterUsage: m,
  latestCost: v,
  questionSummaryMode: y = !1,
  questionSummaryPrompt: k = "",
  onQuestionSummaryPromptChange: b,
  questionSummaryInputPreview: _ = null
}) {
  const N = l > 0,
    C = kn[a] || a,
    F = m?.credits,
    L = m?.key,
    Q = F?.balance,
    R = L?.limit_remaining,
    j = v?.estimated_cost_usd,
    [I, A] = o.useState(!1),
    P = o.useMemo(() => Cn(_), [_]),
    q = o.useMemo(() => Sn(_), [_]),
    S = [a, `${l} response${l === 1 ? "" : "s"}`, N && n ? n : null].filter(Boolean);
  o.useEffect(() => {
    if (!I) return;
    const f = T => {
      T.key === "Escape" && A(!1);
    };
    return document.addEventListener("keydown", f), () => document.removeEventListener("keydown", f);
  }, [I]);
  function w() {
    _ && navigator.clipboard?.writeText(_).catch(() => {});
  }
  function M() {
    if (!_) return;
    const f = new Blob([_], {
        type: "application/json"
      }),
      T = URL.createObjectURL(f),
      z = document.createElement("a");
    z.href = T, z.download = "symphonia-ai-input-preview.json", z.click(), URL.revokeObjectURL(T);
  }
  return e.jsxs(e.Fragment, {
    children: [e.jsxs("details", {
      className: "summary-disclosure",
      children: [e.jsxs("summary", {
        children: [e.jsx("span", {
          children: "Generate synthesis"
        }), e.jsx("small", {
          children: "Model, method and instructions"
        })]
      }), e.jsx("div", {
        className: "card p-4 synthesis-generator",
        style: {
          backgroundColor: "color-mix(in srgb, var(--muted) 20%, var(--card))",
          borderColor: "color-mix(in srgb, var(--border) 58%, transparent)",
          boxShadow: "0 10px 28px rgba(15, 23, 42, 0.04)"
        },
        children: e.jsxs("div", {
          className: "space-y-2.5",
          children: [e.jsxs("div", {
            className: "synthesis-generator-heading",
            children: [e.jsx("h3", {
              children: "Create a draft"
            }), e.jsx("p", {
              children: l + " response" + (l === 1 ? "" : "s") + (N && n ? " · " + n : "")
            })]
          }), e.jsxs("label", {
            className: "block",
            children: [e.jsx("span", {
              className: "mb-1 block text-[11px] font-semibold uppercase tracking-[0.12em]",
              style: {
                color: "var(--muted-foreground)"
              },
              children: "Model"
            }), e.jsx("select", {
              id: "model-select",
              className: "w-full rounded-md px-2.5 py-2 text-xs",
              value: a,
              onChange: f => d(f.target.value),
              style: {
                backgroundColor: "color-mix(in srgb, var(--background) 78%, var(--card))",
                border: "1px solid color-mix(in srgb, var(--border) 62%, transparent)",
                color: "var(--foreground)"
              },
              children: u.map(f => e.jsx("option", {
                value: f,
                children: ct[f] || f
              }, f))
            })]
          }), y ? e.jsxs("div", {
            className: "space-y-2",
            children: [e.jsxs("label", {
              className: "block",
              children: [e.jsx("span", {
                className: "mb-1 block text-[11px] font-semibold uppercase tracking-[0.12em]",
                style: {
                  color: "var(--muted-foreground)"
                },
                children: "Prompt"
              }), e.jsx("textarea", {
                value: k,
                onChange: f => b?.(f.target.value),
                rows: 4,
                className: "w-full resize-none rounded-lg px-3 py-2.5 text-sm leading-6 outline-none transition-colors",
                style: {
                  backgroundColor: "var(--background)",
                  border: "1px solid color-mix(in srgb, var(--border) 72%, transparent)",
                  color: "var(--foreground)",
                  minHeight: "6.25rem"
                },
                placeholder: "Tell the model how to write the question summaries..."
              })]
            }), _ ? e.jsx("div", {
              className: "rounded-lg px-3 py-2 text-xs",
              style: {
                backgroundColor: "color-mix(in srgb, var(--background) 78%, var(--card))",
                border: "1px solid color-mix(in srgb, var(--border) 64%, transparent)"
              },
              children: e.jsxs("div", {
                className: "flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between",
                children: [e.jsxs("div", {
                  className: "min-w-0",
                  children: [e.jsx("div", {
                    className: "font-medium",
                    style: {
                      color: "var(--foreground)"
                    },
                    children: "AI input"
                  }), e.jsxs("p", {
                    className: "mt-0.5 leading-5",
                    style: {
                      color: "var(--muted-foreground)",
                      marginBottom: 0
                    },
                    children: ["Prompt and aggregated ratings", P.questionCount != null ? ` for ${P.questionCount} questions` : "", P.responseCount != null ? ` from ${P.responseCount} responses` : "", "."]
                  })]
                }), e.jsxs("div", {
                  className: "flex shrink-0 items-center gap-1.5",
                  children: [e.jsx("button", {
                    type: "button",
                    onClick: () => A(!0),
                    className: "inline-flex items-center justify-center rounded-md px-2.5 py-1.5 text-[11px] font-semibold",
                    style: {
                      backgroundColor: "var(--card)",
                      border: "1px solid var(--border)",
                      color: "var(--foreground)"
                    },
                    children: "View details"
                  }), e.jsx("button", {
                    type: "button",
                    onClick: w,
                    className: "inline-flex h-8 w-8 items-center justify-center rounded-md",
                    style: {
                      backgroundColor: "var(--card)",
                      border: "1px solid var(--border)",
                      color: "var(--foreground)"
                    },
                    "aria-label": "Copy AI input",
                    title: "Copy",
                    children: e.jsx(Ts, {
                      size: 13,
                      "aria-hidden": "true"
                    })
                  }), e.jsx("button", {
                    type: "button",
                    onClick: M,
                    className: "inline-flex h-8 w-8 items-center justify-center rounded-md",
                    style: {
                      backgroundColor: "var(--card)",
                      border: "1px solid var(--border)",
                      color: "var(--foreground)"
                    },
                    "aria-label": "Download AI input JSON",
                    title: "Download JSON",
                    children: e.jsx(et, {
                      size: 13,
                      "aria-hidden": "true"
                    })
                  })]
                })]
              })
            }) : null]
          }) : e.jsxs("div", {
            className: "space-y-2",
            children: [null, e.jsxs("label", {
              className: "synthesis-field",
              children: [e.jsx("span", {
                children: "Method"
              }), e.jsxs("select", {
                "aria-label": "Method",
                value: s,
                onChange: f => t(f.target.value),
                children: [e.jsx("option", {
                  value: "simple",
                  children: "Simple"
                }), e.jsx("option", {
                  value: "custom",
                  children: "Custom instructions"
                }), e.jsx("option", {
                  value: "committee",
                  children: "Committee"
                }), e.jsx("option", {
                  value: "ttd",
                  children: "Thorough analysis"
                })]
              }), e.jsx("small", {
                children: s === "committee" ? "Multiple perspectives, combined into one draft." : s === "ttd" ? "A deeper review; takes longer." : s === "custom" ? "Add your instructions below." : "A concise synthesis of this round’s responses."
              })]
            }), s === "custom" && e.jsxs("label", {
              className: "block",
              children: [e.jsx("span", {
                className: "mb-1 block text-[11px] font-semibold uppercase tracking-[0.12em]",
                style: {
                  color: "var(--muted-foreground)"
                },
                children: "Custom prompt"
              }), e.jsx("textarea", {
                key: location.pathname,
                defaultValue: localStorage.getItem("symphonia-custom-synthesis-prompt:" + location.pathname) || "",
                onChange: m => localStorage.setItem("symphonia-custom-synthesis-prompt:" + location.pathname, m.target.value),
                rows: 5,
                className: "w-full resize-y rounded-lg px-3 py-2.5 text-sm leading-6 outline-none",
                placeholder: "Tell the model exactly how to synthesise this round...",
                style: {
                  border: "1px solid color-mix(in srgb, var(--border) 72%, transparent)",
                  backgroundColor: "var(--background)",
                  color: "var(--foreground)",
                  minHeight: "7rem"
                }
              }), e.jsx("span", {
                className: "mt-1 block text-xs leading-5",
                style: {
                  color: "var(--muted-foreground)"
                },
                children: "Default output is claim bullets with confidence only. Your prompt is added on top."
              })]
            })]
          }), e.jsxs("details", {
            className: "synthesis-optional",
            children: [e.jsx("summary", {
              children: "Usage and cost"
            }), e.jsxs("div", {
              className: "rounded-lg px-3 py-2 text-xs",
              style: {
                backgroundColor: "color-mix(in srgb, var(--background) 78%, var(--card))",
                border: "1px solid color-mix(in srgb, var(--border) 62%, transparent)",
                color: "var(--muted-foreground)"
              },
              children: [e.jsxs("div", {
                className: "mb-1.5 flex items-center gap-1.5 font-semibold",
                style: {
                  color: "var(--foreground)"
                },
                children: [e.jsx(Rr, {
                  size: 13,
                  "aria-hidden": "true"
                }), "OpenRouter spend"]
              }), e.jsxs("div", {
                className: "grid grid-cols-2 gap-x-3 gap-y-1",
                children: [e.jsx("span", {
                  children: "Balance"
                }), e.jsx("span", {
                  className: "text-right font-medium",
                  style: {
                    color: "var(--foreground)"
                  },
                  children: typeof Q == "number" ? es(Q) : m?.errors?.credits ? "Needs management key" : "N/A"
                }), e.jsx("span", {
                  children: "Key remaining"
                }), e.jsx("span", {
                  className: "text-right font-medium",
                  style: {
                    color: "var(--foreground)"
                  },
                  children: typeof R == "number" ? es(R) : "No cap"
                }), e.jsx("span", {
                  children: "Today"
                }), e.jsx("span", {
                  className: "text-right font-medium",
                  style: {
                    color: "var(--foreground)"
                  },
                  children: es(L?.usage_daily)
                }), e.jsx("span", {
                  children: "Latest run"
                }), e.jsx("span", {
                  className: "text-right font-medium",
                  style: {
                    color: "var(--foreground)"
                  },
                  children: es(j, !0)
                })]
              })]
            })]
          }), e.jsxs("div", {
            className: "synthesis-generate-footer",
            children: [e.jsx("p", {
              children: N ? "Review the draft before publishing." : "Waiting for responses"
            }), e.jsx(be, {
              variant: N ? "accent" : "secondary",
              size: "sm",
              loading: c,
              loadingText: "Generating…",
              onClick: i,
              disabled: !N,
              children: "Generate draft"
            })]
          })]
        })
      })]
    }), I && _ ? e.jsxs("div", {
      className: "fixed inset-0 z-[80]",
      children: [e.jsx("button", {
        type: "button",
        className: "absolute inset-0 h-full w-full cursor-default bg-black/45",
        onClick: () => A(!1),
        "aria-label": "Close AI input preview"
      }), e.jsxs("div", {
        role: "dialog",
        "aria-modal": "true",
        "aria-labelledby": "ai-input-preview-title",
        className: "relative mx-auto my-4 flex max-h-[92vh] w-[min(1120px,94vw)] flex-col overflow-hidden rounded-xl",
        style: {
          backgroundColor: "var(--card)",
          border: "1px solid var(--border)",
          boxShadow: "0 24px 80px rgba(15, 23, 42, 0.28)"
        },
        children: [e.jsxs("div", {
          className: "flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-start sm:justify-between",
          style: {
            borderBottom: "1px solid var(--border)"
          },
          children: [e.jsxs("div", {
            className: "min-w-0",
            children: [e.jsx("h2", {
              id: "ai-input-preview-title",
              className: "text-base font-semibold text-foreground",
              style: {
                margin: 0
              },
              children: "AI input preview"
            }), e.jsx("p", {
              className: "mt-1 text-sm leading-6",
              style: {
                color: "var(--muted-foreground)",
                marginBottom: 0
              },
              children: "This is the prompt and aggregated rating payload used for question-summary generation."
            })]
          }), e.jsxs("div", {
            className: "flex shrink-0 items-center gap-2",
            children: [e.jsxs("button", {
              type: "button",
              onClick: w,
              className: "inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold",
              style: {
                backgroundColor: "var(--background)",
                border: "1px solid var(--border)",
                color: "var(--foreground)"
              },
              children: [e.jsx(Ts, {
                size: 13,
                "aria-hidden": "true"
              }), "Copy"]
            }), e.jsxs("button", {
              type: "button",
              onClick: M,
              className: "inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold",
              style: {
                backgroundColor: "var(--background)",
                border: "1px solid var(--border)",
                color: "var(--foreground)"
              },
              children: [e.jsx(et, {
                size: 13,
                "aria-hidden": "true"
              }), "Download JSON"]
            }), e.jsx("button", {
              type: "button",
              onClick: () => A(!1),
              className: "inline-flex h-9 w-9 items-center justify-center rounded-lg",
              style: {
                backgroundColor: "var(--background)",
                border: "1px solid var(--border)",
                color: "var(--foreground)"
              },
              "aria-label": "Close",
              children: e.jsx(Ee, {
                size: 16,
                "aria-hidden": "true"
              })
            })]
          })]
        }), e.jsx("div", {
          className: "min-h-0 flex-1 overflow-auto p-4",
          children: q ? e.jsxs("div", {
            className: "grid gap-4 lg:grid-cols-[minmax(260px,0.85fr)_minmax(0,1.65fr)]",
            children: [e.jsxs("section", {
              className: "rounded-lg p-4 lg:sticky lg:top-0 lg:self-start",
              style: {
                backgroundColor: "color-mix(in srgb, var(--background) 84%, var(--card))",
                border: "1px solid color-mix(in srgb, var(--border) 72%, transparent)"
              },
              children: [e.jsx("div", {
                className: "mb-2 text-xs font-semibold uppercase tracking-[0.12em]",
                style: {
                  color: "var(--muted-foreground)"
                },
                children: "Prompt"
              }), e.jsx("p", {
                className: "text-sm leading-6",
                style: {
                  color: "var(--foreground)",
                  margin: 0,
                  whiteSpace: "pre-wrap"
                },
                children: q.instruction || "No prompt was provided."
              }), q.return_contract ? e.jsxs("p", {
                className: "mt-3 text-xs leading-5",
                style: {
                  color: "var(--muted-foreground)",
                  marginBottom: 0
                },
                children: ["Expected output: ", q.return_contract]
              }) : null]
            }), e.jsx("div", {
              className: "space-y-3",
              children: (q.questions_and_previous_round_results || []).map((f, T) => e.jsxs("section", {
                className: "rounded-lg p-4",
                style: {
                  backgroundColor: "color-mix(in srgb, var(--background) 84%, var(--card))",
                  border: "1px solid color-mix(in srgb, var(--border) 64%, transparent)"
                },
                children: [e.jsx("div", {
                  className: "flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between",
                  children: e.jsxs("div", {
                    className: "min-w-0",
                    children: [e.jsxs("div", {
                      className: "text-xs font-semibold",
                      style: {
                        color: "var(--muted-foreground)"
                      },
                      children: ["Question ", f.question_number || T + 1]
                    }), e.jsx("h3", {
                      className: "mt-1 text-sm font-semibold leading-6",
                      style: {
                        color: "var(--foreground)",
                        marginBottom: 0
                      },
                      children: f.question || "Untitled question"
                    })]
                  })
                }), e.jsx("div", {
                  className: "mt-3 overflow-x-auto",
                  children: e.jsxs("table", {
                    className: "w-full border-collapse text-left text-xs",
                    children: [e.jsx("thead", {
                      children: e.jsxs("tr", {
                        style: {
                          color: "var(--muted-foreground)"
                        },
                        children: [e.jsx("th", {
                          className: "py-2 pr-3 font-semibold",
                          children: "Criterion"
                        }), e.jsx("th", {
                          className: "px-3 py-2 font-semibold",
                          children: "Strongly disagree"
                        }), e.jsx("th", {
                          className: "px-3 py-2 font-semibold",
                          children: "Disagree"
                        }), e.jsx("th", {
                          className: "px-3 py-2 font-semibold",
                          children: "Neutral"
                        }), e.jsx("th", {
                          className: "px-3 py-2 font-semibold",
                          children: "Agree"
                        }), e.jsx("th", {
                          className: "px-3 py-2 font-semibold",
                          children: "Strongly agree"
                        }), e.jsx("th", {
                          className: "py-2 pl-3 text-right font-semibold",
                          children: "Responses"
                        })]
                      })
                    }), e.jsx("tbody", {
                      children: (f.previous_round_results || []).map(z => e.jsxs("tr", {
                        style: {
                          borderTop: "1px solid color-mix(in srgb, var(--border) 64%, transparent)"
                        },
                        children: [e.jsx("td", {
                          className: "py-2 pr-3 font-medium",
                          style: {
                            color: "var(--foreground)"
                          },
                          children: z.label || "Criterion"
                        }), (z.values || []).slice(0, 5).map((K, G) => e.jsx("td", {
                          className: "px-3 py-2 tabular-nums",
                          style: {
                            color: "var(--foreground)"
                          },
                          children: Number.isFinite(K) ? `${K}%` : "0%"
                        }, G)), e.jsx("td", {
                          className: "py-2 pl-3 text-right tabular-nums",
                          style: {
                            color: "var(--muted-foreground)"
                          },
                          children: typeof z.total == "number" ? z.total : 0
                        })]
                      }, z.label))
                    })]
                  })
                }), f.fallback_summary ? e.jsxs("p", {
                  className: "mt-3 text-xs leading-5",
                  style: {
                    color: "var(--muted-foreground)",
                    marginBottom: 0
                  },
                  children: ["Fallback: ", f.fallback_summary]
                }) : null]
              }, `${f.question_number || T}-${f.question || ""}`))
            })]
          }) : e.jsx("pre", {
            className: "min-h-[28rem] rounded-lg p-4 text-xs leading-6",
            style: {
              backgroundColor: "color-mix(in srgb, var(--foreground) 4%, transparent)",
              color: "var(--foreground)",
              whiteSpace: "pre-wrap",
              wordBreak: "break-word"
            },
            children: _
          })
        })]
      })]
    }) : null]
  });
}
export function DraftFixture(){const [dirty,setDirty]=o.useState(false),[published,setPublished]=o.useState(false);return e.jsxs(e.Fragment,{children:[e.jsx(lt,{activeRound:{round_number:2,synthesis:'Synthetic draft'},contextNote:'This draft is carried forward from Round 1. Update and save it as the Round 2 synthesis.',isDirty:dirty,isPublished:published,onSave:()=>setDirty(false),onRevert:()=>setDirty(false),onTogglePublished:()=>setPublished(!published)}),e.jsx('button',{onClick:()=>setDirty(true),children:'Simulate an edit'})]});}
export function GeneratorFixture(){const [mode,setMode]=o.useState('simple'),[model,setModel]=o.useState('Example model'),[done,setDone]=o.useState(false);return e.jsxs(e.Fragment,{children:[e.jsx(dt,{synthesisMode:mode,onModeChange:setMode,selectedModel:model,onModelChange:setModel,models:['Example model','Another example model'],responseCount:8,estimateLabel:'About 30 seconds',onGenerate:()=>setDone(true)}),done&&e.jsx('p',{role:'status',children:'Preview only — no synthesis generated.'})]});}
