import * as React from 'react';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {createResponseWorkspace} from './responseWorkspace';
import {renderResponseReading} from './responseReading';
const questions=[{questionId:'claim',sectionTitle:'Preserve the exact claim',label:'Your response',inputType:'single_select',options:['Agree','Disagree']}];
const rounds=[{id:2,round_number:2,synthesis:'',is_active:false,questions},{id:3,round_number:3,synthesis:'',is_active:true,questions}];
const answer=(id:number,email:string,round_id:number)=>({id,email,round_id,timestamp:'2026-09-14T10:00:00Z',version:1,answers:{q1:{position:'Agree',evidence:`Original evidence ${id}`},orphan:'Retained unmatched answer'}});
const structuredRounds=[{...rounds[0],responses:[answer(1,'Earlier expert',2)]},{...rounds[1],questions:[],responses:[answer(2,'Alice',3),answer(3,'Bob',3)]}];
const Editor=({questions,response,onUpdated,roundNumber}:any)=><>{renderResponseReading(React.createElement,questions,response.answers,roundNumber)}<button onClick={()=>onUpdated({...response,version:2})}>Save fixture edit</button></>;
const base={rounds,structuredRounds,formQuestions:questions,initialRoundId:3,onResponseUpdated:vi.fn()};
beforeEach(()=>{vi.spyOn(window,'scrollTo').mockImplementation(()=>{});});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('shows all answers for one claim without a separate reader or back navigation',()=>{
 const Workspace=createResponseWorkspace(React,Editor);render(<Workspace {...base}/>);
 expect(screen.getByText('Original evidence 2')).toBeInTheDocument();
 expect(screen.getByText('Original evidence 3')).toBeInTheDocument();
 expect(screen.queryByRole('button',{name:/All responses/})).not.toBeInTheDocument();
 fireEvent.change(screen.getByRole('combobox',{name:'Question or claim'}),{target:{value:'Additional response · orphan'}});
 expect(screen.getAllByText('Retained unmatched answer')).toHaveLength(2);
 fireEvent.click(screen.getByRole('button',{name:'By person'}));
 const alice=screen.getByRole('button',{name:/Alice/}); const bob=screen.getByRole('button',{name:/Bob/});
 fireEvent.click(alice);fireEvent.click(bob);
 expect(alice).toHaveAttribute('aria-expanded','true');expect(bob).toHaveAttribute('aria-expanded','true');
 expect(screen.getAllByText('Retained unmatched answer')).toHaveLength(2);
});
it('compares only identical question wording and retains a participant across rounds',()=>{
 const Workspace=createResponseWorkspace(React,Editor);
 render(<Workspace {...base} structuredRounds={[{...rounds[0],responses:[answer(1,'Alice',2)]},structuredRounds[1]]}/>);
 fireEvent.click(screen.getByRole('button',{name:'Across rounds'}));
 expect(screen.getByText('Original evidence 1')).toBeInTheDocument();
 expect(screen.getByText('Original evidence 2')).toBeInTheDocument();
 expect(screen.getByText('Original evidence 3')).toBeInTheDocument();
 expect(screen.getByText('2 participants · opening perspectives and rating history')).toBeInTheDocument();
});
it('searches all answer fields and distinguishes rounds',()=>{
 const Workspace=createResponseWorkspace(React,Editor);render(<Workspace {...base}/>);
 fireEvent.change(screen.getByRole('combobox',{name:'Round'}),{target:{value:'all'}});expect(screen.getByText('Earlier expert')).toBeInTheDocument();
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'Retained unmatched answer'}});expect(screen.getByText('3 responses found')).toBeInTheDocument();
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'absent'}});expect(screen.getByText('No responses match these filters.')).toBeInTheDocument();
});
it('retains successful deletions and remaining selection when a later deletion fails',async()=>{
 const remove=vi.fn().mockResolvedValueOnce(undefined).mockRejectedValueOnce(new Error('Server unavailable'));const onResponseDeleted=vi.fn();vi.spyOn(window,'confirm').mockReturnValue(true);
 const Workspace=createResponseWorkspace(React,Editor,remove);render(<Workspace {...base} onResponseDeleted={onResponseDeleted}/>);
 fireEvent.click(screen.getByRole('button',{name:'Manage'}));fireEvent.click(screen.getByRole('button',{name:'Select visible'}));fireEvent.click(screen.getByRole('button',{name:'Delete selected'}));
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Server unavailable'));
 expect(onResponseDeleted).toHaveBeenCalledExactlyOnceWith(3,2);expect(screen.getByRole('checkbox',{name:'Select Alice, round 3'})).not.toBeChecked();expect(screen.getByRole('checkbox',{name:'Select Bob, round 3'})).toBeChecked();
});
it('preserves the selected claim across views and does not mark neutral ratings as disagreement',()=>{
 const Workspace=createResponseWorkspace(React,Editor);
 const neutral={...answer(4,'Neutral participant',3),answers:{q1:{position:'Neither agree nor disagree'}}};
 render(<Workspace {...base} structuredRounds={[structuredRounds[0],{...rounds[1],responses:[neutral]}]}/>);
 expect(screen.getByText('Neither agree nor disagree')).toHaveClass('rp-neutral');
 fireEvent.click(screen.getByRole('button',{name:'Across rounds'}));
 expect(screen.getByRole('combobox',{name:'Question or claim'})).toHaveValue('Preserve the exact claim');
});
it('includes the opening response as context without inventing a round-one claim rating',()=>{
 const opening={id:1,round_number:1,is_active:false,synthesis:'',questions:['What matters before testing?']};
 const initial={...answer(9,'Alice',1),answers:{q1:{position:'Start with a useful experiment.'}}};
 const revised={...answer(2,'Alice',3),answers:{q1:{position:'Agree',evidence:'My explanation changed after feedback.'}}};
 const Workspace=createResponseWorkspace(React,Editor);
 render(<Workspace {...base} rounds={[opening,...rounds]} structuredRounds={[{...opening,responses:[initial]},{...rounds[0],responses:[answer(1,'Alice',2)]},{...rounds[1],responses:[revised]}]}/>);
 fireEvent.click(screen.getByRole('button',{name:'Across rounds'}));
 expect(screen.getByText('Start with a useful experiment.')).toBeInTheDocument();
 expect(screen.getAllByText('What matters before testing?').length).toBeGreaterThan(0);
 expect(screen.getByText('Opening perspective')).toBeInTheDocument();
 expect(screen.getByText('First rating')).toBeInTheDocument();
 expect(screen.getByText('After feedback')).toBeInTheDocument();
 expect(screen.getByText('Same rating · explanation changed')).toBeInTheDocument();
 const expand=screen.getByRole('button',{name:'Read full responses'});fireEvent.click(expand);expect(expand).toHaveAttribute('aria-expanded','true');
 expect(screen.getByText('Original evidence 1')).toBeInTheDocument();
});
