import * as React from 'react';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {createResponseWorkspace} from './responseWorkspace';
import {renderResponseReading} from './responseReading';
const questions=[{questionId:'claim',sectionTitle:'Preserve the exact claim',label:'Your response',inputType:'single_select',options:['Agree','Disagree']}];
const rounds=[{id:2,round_number:2,synthesis:'',is_active:false,questions},{id:3,round_number:3,synthesis:'',is_active:true,questions}];
const answer=(id:number,email:string,round_id:number)=>({id,email,round_id,timestamp:'2026-09-14T10:00:00Z',version:1,answers:{q1:{position:'Agree',evidence:`Original evidence ${id}`},orphan:'Retained unmatched answer'}});
const structuredRounds=[{...rounds[0],responses:[answer(1,'Earlier expert',2)]},{...rounds[1],questions:[],responses:[answer(2,'Alice',3),answer(3,'Bob',3)]}];
const Editor=({questions,response,onUpdated,roundNumber}:any)=><>{renderResponseReading(React.createElement,questions,response.answers,roundNumber)}<button onClick={()=>onUpdated({...response,version:2})}>Save fixture edit</button></>;
const base={rounds,structuredRounds,formQuestions:questions,initialRoundId:3,onResponseUpdated:vi.fn()};
beforeEach(()=>{vi.spyOn(window,'scrollTo').mockImplementation(()=>{});});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('reads each person in a dedicated pane while preserving filters and original answers',()=>{
 const Workspace=createResponseWorkspace(React,Editor);render(<Workspace {...base}/>);
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'Original evidence'}});
 const alice=screen.getByRole('button',{name:'Read response from Alice, round 3'});
 fireEvent.click(alice);
 expect(alice).toHaveAttribute('aria-pressed','true');
 expect(screen.getByRole('heading',{name:'Preserve the exact claim'})).toBeInTheDocument();
 expect(screen.getByText('Retained unmatched answer')).toBeInTheDocument();
 expect(screen.getByRole('searchbox')).toHaveValue('Original evidence');
 const bob=screen.getByRole('button',{name:'Read response from Bob, round 3'});
 expect(bob).toBeInTheDocument();
 expect(screen.getByRole('navigation',{name:'Response navigation'})).toBeInTheDocument();
 fireEvent.click(bob);expect(alice).toHaveAttribute('aria-pressed','false');
 fireEvent.click(screen.getByRole('button',{name:'Save fixture edit'}));expect(base.onResponseUpdated).toHaveBeenCalledWith(3,expect.objectContaining({id:3,version:2}));
 fireEvent.click(screen.getByRole('button',{name:'Previous response'}));expect(alice).toHaveAttribute('aria-pressed','true');
 expect(screen.getAllByText('Original evidence 2').length).toBeGreaterThan(0);
});
it('searches all answer fields and distinguishes rounds',()=>{
 const Workspace=createResponseWorkspace(React,Editor);render(<Workspace {...base}/>);
 fireEvent.change(screen.getByRole('combobox'),{target:{value:'all'}});expect(screen.getByRole('button',{name:'Read response from Earlier expert, round 2'})).toBeInTheDocument();
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'Retained unmatched answer'}});expect(screen.getByText('3 responses found')).toBeInTheDocument();
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'absent'}});expect(screen.getByText('No responses match these filters.')).toBeInTheDocument();
});
it('retains successful deletions and remaining selection when a later deletion fails',async()=>{
 const remove=vi.fn().mockResolvedValueOnce(undefined).mockRejectedValueOnce(new Error('Server unavailable'));const onResponseDeleted=vi.fn();vi.spyOn(window,'confirm').mockReturnValue(true);
 const Workspace=createResponseWorkspace(React,Editor,remove);render(<Workspace {...base} onResponseDeleted={onResponseDeleted}/>);
 fireEvent.click(screen.getByRole('button',{name:'Manage'}));fireEvent.click(screen.getByRole('button',{name:'Select visible'}));fireEvent.click(screen.getByRole('button',{name:'Delete selected'}));
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Server unavailable'));
 expect(onResponseDeleted).toHaveBeenCalledExactlyOnceWith(3,2);expect(screen.getByRole('checkbox',{name:'Select Alice, round 3'})).not.toBeChecked();expect(screen.getByRole('checkbox',{name:'Select Bob, round 3'})).toBeChecked();
});
